[tasks]
start = "npm run start"
android = "npm run android"
ios = "npm run ios"
web = "npm run web"
lint = "npm run lint"
"lint:fix" = "npm run lint:fix"
format = "npm run format"
test = "npm run test"
"test:components" = "npm run test:components"
typecheck = "npm run typecheck"
storybook = "npm run storybook"
"storybook:build" = "npm run storybook:build"
setup = "npm ci"
